"""agregue columna fecha vencimiento

Revision ID: 12599a596272
Revises: 6d2086cd85f4
Create Date: 2024-11-29 20:26:55.775809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12599a596272'
down_revision = '6d2086cd85f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.rename_table
    op.rename_table('producto_model', 'productos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('productos', 'producto_model')

    # ### end Alembic commands ###
