"""cambie nombre tabla de product_model a productos

Revision ID: 767d63551488
Revises: 12599a596272
Create Date: 2024-11-29 20:31:24.138205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767d63551488'
down_revision = '12599a596272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=False),
    sa.Column('serie', sa.Text(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.drop_table('producto_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('precio', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('serie', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('disponible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='producto_model_pkey'),
    sa.UniqueConstraint('serie', name='producto_model_serie_key')
    )
    op.drop_table('productos')
    # ### end Alembic commands ###
